replicaCount: 1

image:
  repository:
  tag:
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
#  port: 80
#  containerPort: 80

volumes:
#  - name: base-config
#    hostPath:
#      path: "/appdata/k3s/base"

volumeMounts:
#  - name: base-config
#    mountPath: "/config"

baseEnv:

env:

configmaps:
